Repository CryptoMorin/XSeries, pull requests merged in 2021-03, with the labels that each got.

#106 [XItemStack] Major Changes - Map, Book & SpawnEgg Support
  src/main/java/com/cryptomorin/xseries/XItemStack.java
Labels: bug, documentation, enhancement

#112 [XSound] ENTITY_ZOMBIFIED_PIGLIN_AMBIENT Legacy Name Typo
  src/main/java/com/cryptomorin/xseries/XSound.java
Labels: bug

#107 [XMaterial] Fixed FILLED_MAP Matching in Legacy Versions
  src/main/java/com/cryptomorin/xseries/XMaterial.java
Labels: bug, special case
