Repository CryptoMorin/XSeries, pull requests merged in 2024-06, with the labels that each got.

#259 [XParticle] BARRIER, LIGHT -> BLOCK_MARKER (v1.18)
  src/main/java/com/cryptomorin/xseries/particles/XParticle.java
Labels: bug

#261 [XParticle] v1.20.5 Renaming fix
  src/main/java/com/cryptomorin/xseries/particles/XParticle.java
Labels: bug

#262 [XReflection] Fix load error on versions with no patch
  src/main/java/com/cryptomorin/xseries/reflection/XReflection.java
Labels: bug

#265 [ParticleDisplay] Be generally more user-friendly
  src/main/java/com/cryptomorin/xseries/particles/ParticleDisplay.java
  src/main/java/com/cryptomorin/xseries/particles/Particles.java
Labels: enhancement

#269 [XSound] Re-add play methods with volume and pitch for convenience
  src/main/java/com/cryptomorin/xseries/XSound.java
Labels: enhancement

#271 public XEntity#editBossBar
  src/main/java/com/cryptomorin/xseries/XEntity.java
Labels: enhancement

#274 [XSkull] Legacy support
  src/main/java/com/cryptomorin/xseries/profiles/ProfilesCore.java
  src/main/java/com/cryptomorin/xseries/profiles/mojang/MojangAPI.java
  src/main/java/com/cryptomorin/xseries/profiles/objects/Profileable.java
Labels: bug, enhancement

#279 [XSkull] Support 1.20.1-1.20.5 proxy mappings
  src/main/java/com/cryptomorin/xseries/profiles/ProfilesCore.java
Labels: bug
